 workflows:
  electron-vite-react:
    name: "Electron + Vite + React Build"
    instance_type: linux_x2
    max_build_duration: 120
    
    environment:
      node: 20
      npm: latest
      
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.cache/electron
        - node_modules/.cache
    
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    
    scripts:
      - name: "Setup project"
        script: |
          echo "Projet Electron détecté"
          ls -la
          cat package.json | grep electron || echo "Electron non trouvé"
          
      - name: "Install dependencies"
        script: npm ci
        
      - name: "Build Vite + React"
        script: npm run build
        
      - name: "Electron Builder"
        script: |
          npx electron-builder \
            --linux deb rpm AppImage \
            --win nsis \
            --mac dmg \
            --publish=never
    
    artifacts:
      - dist/**/*.deb
      - dist/**/*.rpm
      - dist/**/*.AppImage
      - dist/**/*.exe
      - dist/**/*.nsis
      - dist/*.dmg
      - dist/*.zip
